<?php
/**
 * @file
 * A page module that allows users to create and order custom business cards.
 */

/**
 * Implements hook_help().
 */
function card_creator_help($path, $arg) {
  switch ($path) {
    case "admin/help#card_creator":
      return '<p>' . t("Allows users to create a custom business card") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function card_creator_menu() {
	$items = array();
	$items['card_creator'] = array( //this creates a URL that will call this form at card_creator
		'description' => 'Customize your business card!.',
		'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form use drupal_get_form
		'page arguments' => array('card_creator_form'), //put the name of the form here
		'access callback' => TRUE,
	);

	return $items;
} 

/**
 * Build card creation form
 */ 
function card_creator_form($form, &$form_state) {

	// Attach css, js, and library files
	$form['#attached']['css'] = array(
  	drupal_get_path('module', 'card_creator') . '/css/styles.css',
	);

	// Input Fields
	$form['company_name'] = array(
		'#type' => 'textfield',
		'#id' => 'companyName',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Company Name'),
		),
		'#prefix' => '<div id="container"><div id="leftColumn"><div id="cardInfo">',
	);
	$form['name'] = array(
		'#type' => 'textfield',
		'#id' => 'name',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Name'),
		),
	);
	$form['title'] = array(
		'#type' => 'textfield',
		'#id' => 'title',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Title'),
		),
	);
	$form['address'] = array(
		'#type' => 'textfield',
		'#id' => 'address',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Address'),
		),
	);
	$form['city_state_zip'] = array(
		'#type' => 'textfield',
		'#id' => 'cityStateZip',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Company Name'),
		),
	);
	$form['line1'] = array(
		'#type' => 'textfield',
		'#id' => 'line1',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Line 1'),
		),
	);
	$form['line2'] = array(
		'#type' => 'textfield',
		'#id' => 'line2',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => t('Line 2'),
		),
	);
	$form['line3'] = array(
		'#type' => 'textfield',
		'#id' => 'line3',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => ('Line 3'),
		),
	);
	$form['line4'] = array(
		'#type' => 'textfield',
		'#id' => 'line4',
		'#size' => 30,
		'#attributes' => array(
			'placeholder' => ('Line 4'),
		),
		'#suffix' => '</div>',
	);

	// Clipart Color Label
	$form['clipart_color'] = array(
		'#id' => 'clipartColor',
		'#markup' => '<label>' . t('Clipart Color') . '</label>',
	);

	// Font Family Select List
	$form['font_family'] = array(
		'#type' => 'select',
		'#id' => 'docFontFamily',
		'#options' => array(
			0 => t('Helvetica'),
			1 => t('Futura'),
			2 => t('Garamond'),
			3 => t('Frutiger'),
		),
		'#suffix' => '</div>',
	);

	// Preview svg
	$form['preview'] = array(
		'#markup' => '<svg id="preview"></svg>',
		'#prefix' => '<div id="rightColumn">',
		'#suffix' => '</div>', 
	);

	// Clipart selection
	$form['select_clipart'] = array(
		'#markup' => '<h4>' . t('Select Clipart') . '</h4>',
		'#prefix' => '<div id="bottom"><div id="bottomLeftCol"><div id="bottomLeftColUpper">',
		'#suffix' => '</div>',
	);
	$form['vehicles'] = array(
		'#type' => 'button',
		'#id' => 'vehicles',
		'#value' => t('Vehicles'),
		'#prefix' => '<div id="bottomLeftColLowerLeft">',
	);
	$form['manufacturer'] = array(
		'#type' => 'button',
		'#id' => 'manufacturer',
		'#value' => t('Manufacture Logo\'s'),
	);
	$form['animals'] = array(
		'#type' => 'button',
		'#id' => 'animals',
		'#value' => t('Animals'),
		'#suffix' => '</div>',
	);

	// Clipart svg dispaly
	$form['clipart'] = array(
		'#markup' => '<svg id="clipart"></svg>',
		'#prefix' => '<div id="bottomLeftColLowerRight">',
		'#suffix' => '</div></div>',
	);

	// Ink Color Selection
	$form['select_ink_color'] = array(
		'#markup' => '<h4>' . t('Select Ink Color') . '<h4>',
		'#prefix' => '<div id="bottomRightCol"><div id="bottomRightMid"><div id="bottomRightMidUpper">',
		'#suffix' => '</div>',
	);

	// One Color Options
	$form['black'] = array(
		'#type' => 'button',
		'#value' => t('Black'),
		'#prefix' => '<div id="bottomRightMidLower"><div id="oneColor">',
	);
	$form['red'] = array(
		'#type' => 'button',
		'#value' => t('Red'),
	);
	$form['blue'] = array(
		'#type' => 'button',
		'#value' => t('Blue'),
	);
	$form['maroon'] = array(
		'#type' => 'button',
		'#value' => t('Maroon'),
	);
	$form['green'] = array(
		'#type' => 'button',
		'#value' => t('Green'),
	);
	$form['brown'] = array(
		'#type' => 'button',
		'#value' => t('Brown'),
		'#suffix' => '</div>',
	);

	// Two Color Options
	$form['red_blue'] = array(
		'#type' => 'button',
		'#value' => t('Red/Blue'),
		'#prefix' => '<div id="twoColors">',
	);
	$form['red_black'] = array(
		'#type' => 'button',
		'#value' => t('Red/Black'),
	);
	$form['blue_black'] = array(
		'#type' => 'button',
		'#value' => t('Blue/Black'),
	);
	$form['maroon_black'] = array(
		'#type' => 'button',
		'#value' => t('Maroon/Black'),
	);
	$form['green_black'] = array(
		'#type' => 'button',
		'#value' => t('Green/Black'),
	);
	$form['brown_black'] = array(
		'#type' => 'button',
		'#value' => t('Brown/Black'),
		'#suffix' => '</div></div></div>'
	);

	// Template Selection
	$form['select_template'] = array(
		'#markup' => '<h4>' . t('Select A Template') . '</h4>',
		'#prefix' => '<div id="bottomRightSide"><div id="bottomRightSideUpper">',
		'#suffix' => '</div>',
	);

	// Templates svg display
	$form['templates'] = array(
		'#markup' => '<svg id="templates"></svg>',
		'#prefix' => '<div id="bottomRightSideLower">',
		'#suffix' => '</div></div></div></div>',
	);

	$form['#attached']['js'][] = array(
    'data' => drupal_get_path('module', 'card_creator') . '/js/card_creator.js',
    'type' => 'file',
  );

	return $form;
}

function card_creator_form_validate($form, &$form_state) {
}

function card_creator_form_submit($form, &$form_state) {
}
































