<?php
/**
 * @file
 * A module that allows users to upload custom business cards.
 */

/**
 * Implements hook_help().
 */
function silver_package_help($path, $arg) {
  switch ($path) {
    case 'admin/help#silver_package':{
      $ret_val = '<h3>' . t('About') . '</h3>';
      $ret_val .= '<p>' . t('Allows customers to select products as part of a Silver Package.') . '</p>';
      return $ret_val;
      break;
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function silver_package_form_alter(&$form, &$form_state, $form_id) {
  $quantity = array(
    '0' => '0',
    '1' => '1',
    '2' => '2',
    '3' => '3',
    '4' => '4',
    '5' => '5',
    '6' => '6',
    '7' => '7',
    '8' => '8',
    '9' => '9',
    '10' => '10',
  );
  if (strpos($form_id, 'add_to_cart_form')) {
    $bundle = $form['line_item_fields']['commerce_product']['und']['#bundle'];
    if (strpos($bundle, '_sp') !== false) {
      $form['#attached']['css'] = array(
        drupal_get_path('module', 'silver_package') . '/css/silver_package.css',
      );

      $product_options = $form['line_item_fields']['field_product_1']['und']['#options'];
      $i = 0;
      foreach ($product_options as $option => $value) {
        if ($value !== '- None -') {
          $product_name = explode(': ', $value);
          $product_name = $product_name[1];
          $form['product_' . $i] = array(
            '#type' => 'checkbox',
            '#title' => t($product_name),
            '#id' => $option, 
            '#prefix' => '<div class="silver_package_product"><div class="silver_package_product_select">',
            '#suffix' => '</div>',
          );
          $form['product_quantity_' . $i] = array(
            '#type' => 'select',
            '#options' => $quantity,
            '#default_value' => '0',
            '#prefix' => '<div class="silver_package_product_quantity">',
            '#suffix' => '</div></div>',
          );
        };        
        $i++;
      };

      $form['#submit'][0] = 'silver_package_form_submit';

      $form['#attached']['js'][] = array(
        'data' => drupal_get_path('module', 'silver_package') . '/js/silver_package.js',
      );
      return $form;
    }
  }
}

/**
 * Validates Camera Ready Form.
 */
function silver_package_form_validate($form, &$form_state) {

}

/**
 * Process a validated Camera Ready Form submission.
 */
function silver_package_form_submit($form, &$form_state) {
  global $user;
  $selected_products = array();
  $values = $form_state['values'];

  // Fetch Selected Products and Store in $selected_products array
  foreach ($values as $name => $value) {
    if (strpos($name, 'product_') !== false && $name !== 'product_id' && strpos($name, 'product_quantity') === false) {
      if ($value !== 0) {
        $selected_products[] = $form[$name]['#id'];
      }
    }
  }

  // First, see if there is already a cart for this user.
  if (module_exists('commerce_cart')) {
    $order = commerce_cart_order_load($user->uid);
  }
  if (empty($order)) {
    // Create the new order in checkout
    $order = commerce_order_new($user->uid, 'checkout_checkout');
    // Save the order to get its ID.
    commerce_order_save($order);
  }
  // Link anonymous user session to the cart
  if (!$user->uid) {
    commerce_cart_order_session_save($order->order_id);
  }

  // Load Black Tie Collection Silver Package and create a line item for it.
  $product_id = 84;
  $product = commerce_product_load($product_id);
  $line_item = commerce_product_line_item_new($product, 1, $order->order_id, array(), 'black_tie_collection_sp');
  // Add the custom values to the line_item fields
  foreach ($selected_products as $product => $value) {
    $line_item->field_product_1['und'][0]['product_id'] = $selected_products[0];
    $line_item->field_product_2['und'][0]['product_id'] = $selected_products[1];
    $line_item->field_product_3['und'][0]['product_id'] = $selected_products[2];
    $line_item->field_product_4['und'][0]['product_id'] = $selected_products[3];
    $line_item->field_product_5['und'][0]['product_id'] = $selected_products[4];
    $line_item->field_product_6['und'][0]['product_id'] = $selected_products[5];
    $line_item->field_product_7['und'][0]['product_id'] = $selected_products[6];
    $line_item->field_product_8['und'][0]['product_id'] = $selected_products[7];
    $line_item->field_product_9['und'][0]['product_id'] = $selected_products[8];
    $line_item->field_product_10['und'][0]['product_id'] = $selected_products[9];
  }
  dpm(get_defined_vars());
  // Save the line item to get its ID.
  commerce_line_item_save($line_item);
  // Add the line item to the order using the wrapper.
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $order_wrapper->commerce_line_items[] = $line_item;
  // Save the order again to update its line item reference field.
  commerce_order_save($order);
}
